name: arrabiz_website
description: Arrabiz Website
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  velocity_x: ^2.6.1
  google_fonts: ^2.0.0
  flutter_svg: ^0.21.0+1
  transparent_image: ^2.0.0
  url_launcher: ^6.0.3
  material_design_icons_flutter: ^4.0.5955

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/mockup.png
    - assets/waves.svg
    - assets/invoice.png
    - assets/backup.png
    - assets/reports.png
